/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlayerService } from "../player.service";
import { PlayerCreateInput } from "./PlayerCreateInput";
import { Player } from "./Player";
import { PlayerFindManyArgs } from "./PlayerFindManyArgs";
import { PlayerWhereUniqueInput } from "./PlayerWhereUniqueInput";
import { PlayerUpdateInput } from "./PlayerUpdateInput";
import { EnterpriseFindManyArgs } from "../../enterprise/base/EnterpriseFindManyArgs";
import { Enterprise } from "../../enterprise/base/Enterprise";
import { EnterpriseWhereUniqueInput } from "../../enterprise/base/EnterpriseWhereUniqueInput";
import { LandmarkFindManyArgs } from "../../landmark/base/LandmarkFindManyArgs";
import { Landmark } from "../../landmark/base/Landmark";
import { LandmarkWhereUniqueInput } from "../../landmark/base/LandmarkWhereUniqueInput";

export class PlayerControllerBase {
  constructor(protected readonly service: PlayerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Player })
  async createPlayer(@common.Body() data: PlayerCreateInput): Promise<Player> {
    return await this.service.createPlayer({
      data: data,
      select: {
        balance: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Player] })
  @ApiNestedQuery(PlayerFindManyArgs)
  async players(@common.Req() request: Request): Promise<Player[]> {
    const args = plainToClass(PlayerFindManyArgs, request.query);
    return this.service.players({
      ...args,
      select: {
        balance: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async player(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    const result = await this.service.player({
      where: params,
      select: {
        balance: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePlayer(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() data: PlayerUpdateInput
  ): Promise<Player | null> {
    try {
      return await this.service.updatePlayer({
        where: params,
        data: data,
        select: {
          balance: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePlayer(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    try {
      return await this.service.deletePlayer({
        where: params,
        select: {
          balance: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/companies")
  @ApiNestedQuery(EnterpriseFindManyArgs)
  async findCompanies(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Enterprise[]> {
    const query = plainToClass(EnterpriseFindManyArgs, request.query);
    const results = await this.service.findCompanies(params.id, {
      ...query,
      select: {
        bundle: true,
        color: true,
        createdAt: true,
        description: true,
        diceValue: true,
        id: true,
        name: true,

        player: {
          select: {
            id: true,
          },
        },

        price: true,
        profit: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/companies")
  async connectCompanies(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: EnterpriseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companies: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/companies")
  async updateCompanies(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: EnterpriseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companies: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/companies")
  async disconnectCompanies(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: EnterpriseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      companies: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/landmarks")
  @ApiNestedQuery(LandmarkFindManyArgs)
  async findLandmarks(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Landmark[]> {
    const query = plainToClass(LandmarkFindManyArgs, request.query);
    const results = await this.service.findLandmarks(params.id, {
      ...query,
      select: {
        bonus: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,

        player: {
          select: {
            id: true,
          },
        },

        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/landmarks")
  async connectLandmarks(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: LandmarkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      landmarks: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/landmarks")
  async updateLandmarks(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: LandmarkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      landmarks: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/landmarks")
  async disconnectLandmarks(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: LandmarkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      landmarks: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
